version: '3.7'

networks:
  frontend:
  backend:

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  php:
    build:
      context: ./docker/php
      network: host
      # args:
      #   UID: 1000
      #   GID: 1000
    volumes:
      - './www/:/var/www/'
    environment:
      docker: 'true'
    networks:
      - backend
    ports:
      - 9000:9000

  httpd:
    build:
      context: ./docker/httpd
      network: host
    depends_on:
        - php
        - db
    volumes:
      - './www/:/var/www/'
      - './docker/httpd/sites-enabled/:/etc/apache2/sites-enabled/'
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443

  adminer:
    image: adminer
    depends_on:
        - db
    # restart: always
    networks:
      - backend
    ports:
      - 8080:8080