version: '3.7'

networks:
  frontend:
  backend:

services:

  dbapp:
    container_name: "lamp-dbapp"
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
    ports:
      - "3306:3306"

  php:
    container_name: "lamp-php"
    build:
      context: ./.docker/php
      network: host
      args:
        USER_ID:  1000
        GROUP_ID: 1000
    restart: unless-stopped
    depends_on:
      - dbapp
    volumes:
      - './:/web/'
    environment:
      docker: 'true'
    networks:
      - backend
    ports:
      - 9000:9000

  httpd:
    container_name: "lamp-httpd"
    build:
      context: ./.docker/httpd
      network: host
    restart: unless-stopped
    depends_on:
        - php
        - dbapp
    volumes:
      - './:/web/'
      - './.docker/httpd/sites-enabled/:/etc/apache2/sites-enabled/'
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
